stickers = [
    'CAACAgIAAxkBAAEBbVdffWPY8edtrF9Psqit-H_g7yaccgACXwkAAnlc4gmQgI15mUdi-hsE',
    'CAACAgIAAxkBAAEBbVVffWPI3u0WTNEajX2Bd9RAoePahwACTwkAAnlc4gkq22o1wb7e2hsE',
    'CAACAgIAAxkBAAEBbVlffWPdyU70FWkOoiIw5pywdlbo5wACUwkAAnlc4gnTg5_qPcJpexsE',
    'CAACAgIAAxkBAAEBbVtffWSSChPSTPwjYfzPDsXSa8T9dwACSgkAAnlc4glshq449fyDqBsE',
    'CAACAgIAAxkBAAEBTDFfU7W0oczflZY27lV-KljlkPg0TQACZgkAAnlc4gmfCor5YbYYRBsE',
    'CAACAgIAAxkBAAECcuNgze4C8I0GpOYpxU8VFZhMr0G6OwACTgkAAnlc4gk_IdyrDKJmzx8E',
    'CAACAgIAAxkBAAECcuVgze4Xk6mpAdeFLjGnEaFEOA5IwgACRwkAAnlc4glEzGEDHvRUIx8E',
    'CAACAgIAAxkBAAECcudgze4lTSncY23el45msFfI6c1_AwACVwkAAnlc4gkrJAHADxlVXh8E',
    'CAACAgIAAxkBAAECculgze4yK6oixSLcXA9qnbSb7ZT11QACUAkAAnlc4gn1AAE2sQABMfNIHwQ',
    'CAACAgIAAxkBAAECcutgze5GU-q7oj6UoNmZ3wHpVj4nRwACVQkAAnlc4gmvWpq5XkZ_cR8E'
]